### ISSUE TITLE
本地启动后报错无法定位

### ISSUE THREAD

**Issue by WaSheep** [alanWongsGithub/vue-weather#1]
<img width="722" alt="2017-05-20 16 57 09" src="https://cloud.githubusercontent.com/assets/17945318/26274478/6972b836-3d7d-11e7-9690-b8437c7c0196.png">

启动环境: 
mac serria 10
chrome 57.0.2987.98 (64-bit)

应用虽已启动, 担报错如图所以无法定位,跪求解答,谢谢

**Comment by l20** [comment]
- [x] 如上报错是因为数据请求有些滞后，未请求到数据就已经在模板里引用，先代码已在父级元素用v-if指令判断处理。
- [x] IP定位问题已经更换[API](https://bird.ioliu.cn)，因为百度API不能跨域，node上做了代理但请求到的地址是所部署在服务器的地址。所以必须在前端请求才能得到正确的地址，目前已经解决定位问题。
可访问线上版本：[http://weather.alanwong.tech/](http://weather.alanwong.tech/)
